### ISSUE TITLE
Limit the observation space for the start and goal position to a reasonable range

### ISSUE THREAD

**Issue by Erfi** [shamilmamedov/flexible_arm#10]
**Description**:
The observation space for the flexible arm environment needs to be setup such that the starting location of the robot and the desired goal position are within a reasonable range of the workspace

**Implementation**:
Check what the range of values should be for each dimension of the observation space and change the values accordingly in the code.

**Acceptance Criteria**:
```env.reset()``` +  ```env.render()``` in a loop should show the robot start and goal positions to be in the desired range.

**Comment by shamilmamedov** [comment]
Starting to merge my branch with main, and broken Ubuntu😅 Gonna work on the issue as soon as I fix it

**Comment by shamilmamedov** [comment]
Generating reasonable start configuration and goal position was not possible in presence of a wall obstacle using only end-effector position. To avoid cases as shown below in the figure, I generated a function for computing the elbow position of the robot. Now, by checking that neither elbow nor the end-effector is behind the wall, we can make sure that the start configuration and the goal position are adequate and reachable.  

@RudolfReiter I think you should also constrain the elbow position in the NMPC formulation.

![image](https://github.com/shamilmamedov/flexible_arm/assets/59015432/8ab5fefe-2d1b-440f-b651-0bcc24474d21)

**Comment by shamilmamedov** [comment]
Closing the issue for now. If you notice any weird sampled configuration, feel free to open it again.
