### ISSUE TITLE
Goal position should be visible in the GUI as a globe

### ISSUE THREAD

**Issue by Erfi** [shamilmamedov/flexible_arm#11]
**Description**:
Both for the purpose of debugging and for aesthetic reasons, the desired goal position should be visible.

**Implementation**:
Make a call withing the ```reset()``` to the simulation and create the goal sphere according to the position sampled from the observation space.

**Acceptance Criteria**:
Call to ```env.reset()``` +  ```env.render()``` should show the desired goal as a sphere (preferably colored in a visible way).

**Comment by Erfi** [comment]
I looked at your solution, but then figured that we could just add the goal sphere after loading the Robot's URDF (programmatically). See commit above (b8d29b5). This will make is easier to reset the goal as well.

**Comment by Erfi** [comment]
@shamilmamedov I will close this issue with this fix. Let me know what you think.

**Comment by shamilmamedov** [comment]
That's indeed a neat solution. I haven't worked with Panda3d visualizer directly. It seems that you define only once before starting the visualization. My solution that involves an overhead of changing a URDF allows changing the goal position on the fly allowing not only stationary goal, but also a moving ones. We have to think which solution is the best in the long run.

**Comment by Erfi** [comment]
I see. The points (spheres) can also be moved using the pandas3d, but if we are talking about the objects that are attached to the robot, I agree that they should be part of the URDF. So perhaps the following can be done:

- For **Imaginary** (not attached to the physical robot: no mass, no collision) we can use the **panda3d engine** to create them
- For **physical objects** that influence the robot (have mass, possible collision) we add them to the **URDF** (example: the wall)

**Comment by shamilmamedov** [comment]
I like your way of reasoning, but I would go even one step further and separate the robot from the environment. The whole thing can be done as follows:

- In the URDF define only the robot
- The environment takes the robot model and obstacles (Define class for an obstacle)

The reason why this solution is better because obstacles are not gonna be fixed and could be changed programmatically. Unfortunately, this solution would take more time to implement. Let me know if you think it is worth it

**Comment by Erfi** [comment]
Just to write down what we discussed in the call. I like you idea of dynamic obstacles, but this will:
1- Take more time
2- Become a transfer learning setting

This might be too difficult of a problem to solve for ICRA 2024. The dynamic goal sampling is already generalizing the environment to the multi-tasking problem!

So for now we will stick to multi-tasking, and leave the multi-tasking + transfer learning for next time!
