### ISSUE TITLE
Add the wall to the URDF tree

### ISSUE THREAD

**Issue by Erfi** [shamilmamedov/flexible_arm#14]
**Description**:
There is a wall (or should be) in the simulation near the goal point. If the objective is not to hit the wall it makes sense to draw the wall as part of the URDF both for drugging and for visualization purposes. 

**Implementation**:
Change the URDF tree to include a wall, in the correct place. 

**Acceptance Criteria**:
Running the simulation (e.g. ```tests/test_mpc_data_collection.py```) should show the wall as well as the robot arm in the environment.

**Comment by shamilmamedov** [comment]
The wall has been placed on Y-axis at -0.15cm from the origin as shown in the Figure. @RudolfReiter, please change the MPC formulation accordingly

![flexible_arm_wall drawio](https://github.com/shamilmamedov/flexible_arm/assets/59015432/12bccb8f-a4e5-4d00-b5d2-c4808aaf97d4)

**Comment by RudolfReiter** [comment]
Wait, didn't we want to put the position of the wall in the observation?

**Comment by shamilmamedov** [comment]
We can definitely do it. But do we need to if the wall is fixed? The NN should implicitly learn it. @Erfi any thoughts on that?

**Comment by RudolfReiter** [comment]
In order to keep it general and for further experiments, I would put it there.

**Comment by shamilmamedov** [comment]
Sounds good to me. How shall we represent it? One way could be (x,y,z,w,h):

- (x, y, z) of the center of the wall plane
- w  width
- h height

In our case, in the world frame:  (x,y,z) = (0, -0.15, 0), w=2, h=1

**Comment by RudolfReiter** [comment]
It should not be a non-convex constraint. I would have it defined as a halfspace in three dimensions, which needs two vectors of size 3.

**Comment by shamilmamedov** [comment]
I understand that for the NMPC it makes sense to define the wall as a convex-constraint. But for the NN policy can we choose different representation more consistent with the perception?

**Comment by RudolfReiter** [comment]
Hmm, I mean its a design choice if we want to consider halfspace constraints or cubes. I would include first halfspace constraints and maybe later for RL experiments only, include cubes.

**Comment by Erfi** [comment]
I think the NN will automatically learn not to go there, especially since it is not changing it will be a constant value to the input of the network so it won't really add any more information to the NN. However we can still pass it to the NMPC by packing it in the observation and remove it when we pass it to the NN as input.

**Comment by RudolfReiter** [comment]
@Erfi I think what would be a good experiment is to have the wall position as a parameter also for the NN
