### ISSUE TITLE
Environment and expert options

### ISSUE THREAD

**Issue by shamilmamedov** [shamilmamedov/flexible_arm#25]
Hi guys!

Here, I'd like to discuss the environment and expert NMPC options in line with the statements made in the paper. The main points are:

- The computation time of the approximate MPC policy is significantly less than that of NMPC.
- Consequently, the control rate of ANMPC is much higher than that of NMPC, which allows us to handle model-plant mismatch and other disturbances more effectively.

While it's true that NMPC enables you to adjust the sampling time as needed, this doesn't apply to the learned policy, as it relies on the expert NMPC's sampling time. It wouldn't be reasonable to gather expert data at 250Hz for training the policy and then deploy the policy at a different frequency.

On the other hand, the sampling time of the final controller NN + safety filter will be limited by the sampling rate of the safety filter. @RudolfReiter, could you provide insight into how fast we can set up the safety filter? We should select `tf` and `n` of the expert NMPC in a way that aligns with the `tf` and `n` of the safety filter. And finally, set `dt` of the environment accordingly.

**Comment by RudolfReiter** [comment]
Hi!
I think that it should not be a big issue, using a NN with a different frequency than it was trained with. The MPC approximates anyways a the control of an continuous system. The only missmatch would be the zero order hold difference,  but I expect that a minor thing.
However, what you say is also strictly speaking true. From what we have written in the paper, the mean comp. time of the SF was ~3.6ms, max. 7.3ms. I think it is fine to have a period of 4ms and limit the qp iterations such that we do not exceed it.
What do you think?

**Comment by shamilmamedov** [comment]
Hi! The MPC solution is piecewise constant signals. By choosing MPC sampling time which is different from actual sampling time we either limit the preview by choosing `dt_mpc < dt_real` or limiting the performance by holding the input for too long in the case of `dt_mpc > dt_real`. Therefore, I agree that we fix `dt` of the MPC expert and SF to 4ms

**Comment by shamilmamedov** [comment]
As the deadline is approaching I propose to finalize the environment, controller and estimator options:

```
# Environment
env_options = FlexibleArmEnvOptions(
        n_seg=5,
        n_seg_estimator=3,
        sim_time=1.5,
        dt=0.004,
        qa_range_start=np.array([-np.pi/2, 0., -np.pi+0.05]),
        qa_range_end=np.array([3*np.pi/2, np.pi, np.pi-0.05]),
        contr_input_states=StateType.ESTIMATED,  
        sim_noise_R=np.diag([*R_Q, *R_DQ, *R_PEE]),
        render_mode="human",
    )

# Controller
fa_sym_mpc = SymbolicFlexibleArm3DOF(3)
mpc_options = Mpc3dofOptions(n_seg=3, tf=0.5, n=125)
controller = Mpc3Dof(model=fa_sym_mpc, x0=None, pee_0=None, options=mpc_options)
```

I am going to set these parameters in the `gym_utils.py`. We should use the same environment parameters in the evaluation as well. 

@Erfi In the network architecture, can you add a final layer as scaled `tanh` so that we never exceed the control input constraints? The limits are `- np.array([20, 10, 10])` to `np.array([20, 10, 10])`

**Comment by Erfi** [comment]
so after some investigation: SACPolicy already scales the outputs to the correct range of the action_space:

https://github.com/DLR-RM/stable-baselines3/blob/5c93e9f4261f21798fdb4618dc9b33f7d4986350/stable_baselines3/common/policies.py#L379-L387

    def unscale_action(self, scaled_action: np.ndarray) -> np.ndarray:
        """
        Rescale the action from [-1, 1] to [low, high]
        (no need for symmetric action space)


        :param scaled_action: Action to un-scale
        """
        low, high = self.action_space.low, self.action_space.high
        return low + (0.5 * (scaled_action + 1.0) * (high - low))
