### ISSUE TITLE
Add parametric wall

### ISSUE THREAD

**Issue by RudolfReiter** [shamilmamedov/flexible_arm#31]
The parametric wall should be part of the observation, sampling, MPC and safety filter.
The wall parameters are exactly two 3D vectors. a vector from the origin to the wall and the normal vector pointing towards the feasible region.

@shamilmamedov , @Erfi : Please think of a way where to integrate it.

**Comment by shamilmamedov** [comment]
You mean I should add it to the outputs/measurements of the system?

**Comment by RudolfReiter** [comment]
Yes, such as the goal.

**Comment by shamilmamedov** [comment]
I'm not sure what is the best way to add them. On the one hand, for the estimator EKF the goal and the wall do not add any extra information to improve the estimation. 

We should somehow separate the environment observations and the robots observations/measurements. Any ideas how to effectively add new observations?

**Comment by RudolfReiter** [comment]
Hi.
Along the lines of these gym environments, everything should be passed in the observation. @Erfi pointed that out.

Regarding the hyperplane, see this link https://reference.wolfram.com/language/ref/Hyperplane.html

**Comment by shamilmamedov** [comment]
Thank you for the link, I found the parameters of the hyperplane. If we define the constraint as $w^T x \geq b$ where $x$ is $x$ the state, then $w = [0, 1, 0]$ and $b = [0, -0.15, 0.5]$. 

Right now the observation $o = [x, p_goal]$ is the estimated state $x$ and the final goal position $p_goal$. I am going to stack to it the the wall parameters, so the new observation is going to be $o = [x, p_goal, w, b]$

@RudolfReiter  @Erfi  let me know if you are okay with it?

**Comment by Erfi** [comment]
I suggest not adding them to the observation space but setting them in the environment as an attribute. My reasoning is that those values currently do not change hence they don't add any info for the RL, IRL algorithms. If we keep them in the env, we can modify the ```CallableMPCExpert``` class to take them in through it's ```__init__``` just like it's taking the ```env.observation_space```

**Comment by shamilmamedov** [comment]
Imho, the wall parameters provide the context to the network. For this reason and also for easy generalization to moving obstacles in the future, we might already add the wall parameters to the observation vector. Do you agree?

**Comment by RudolfReiter** [comment]
I agree with shamil to have them in the observation space. I guess the RL policy will just ignore the parameters, if they dont change, without a significant drop of performance. Do you agree @Erfi? Shamil, maybe you can add the parameters as tuple (w,b)?

**Comment by shamilmamedov** [comment]
Right now the observation is a numpy array. Adding constraint as a tuple will mess up the representation. Shall we make an observation as a list or tuple of (x, p_goal, obstcles)?
