### ISSUE TITLE
Timing the inference process for different algorithms. 

### ISSUE THREAD

**Issue by Erfi** [shamilmamedov/flexible_arm#35]
**Description**: 
we would like to be able to time the inference of difference algorithms and report them compared to each other. 

**Implementation Suggestion**:
Simple: Since the success of failure of the algorithm here is not the concern we could just have a script that sets an environment and runs each algorithm for N-number of steps (1000?) and reports the average inference per step time time. 
Over Engineered: Create a ```TimeIt``` wrapper and wrap each algorithm with a ```TimeIt``` wrapper. The wrapper adds a moving average (or just an array) to the policy and measures and adds every time the ```predict``` function is called.

I would go with the simple solution.

**Comment by Erfi** [comment]
@RudolfReiter Does this answer one of the concerns in #29 ?

**Comment by Erfi** [comment]
got it, I will follow the instructions [here](https://deci.ai/blog/measure-inference-time-deep-neural-networks/) for timing of the NN. For the MPC I will get back to you and ask for help if need be.

**Comment by Erfi** [comment]
![inference_time_comparison](https://github.com/shamilmamedov/flexible_arm/assets/3267547/c08765f2-e230-4195-9afe-cb3ab2e1cb93)

**Comment by Erfi** [comment]
Do we want to add the safety filter as well? 🤔 It will be applied on top of both MPC and NeuralNet controller so adding it to the same plot can be misleading. Any suggestions?

**Comment by Erfi** [comment]
oh I see, so MPC already includes the safety considerations. Cool, thanks will add another bar NN + Safety as you suggested.

**Comment by RudolfReiter** [comment]
Awesome!

**Comment by shamilmamedov** [comment]
Imho, inference time sounds OK for MPC as well, alternative options could be "Policy Evaluation Time"

**Comment by RudolfReiter** [comment]
Maybe "online computation time"?

**Comment by RudolfReiter** [comment]
Btw. 2) I mean, there is no bound on the computation time of MPC, but of course it will converge at some point or throw an error otherwise. So, I was just suggesting to also include the outliers in the plot. What are the two margins you show? Maybe a standard boxplot with outliers would be best?

**Comment by Erfi** [comment]
btw. 2) what I am showing is the standard deviation. How would the outliers look like? I am not showing them because they don't happen when I run the timing code. Can we just mention it in text? I am just wondering how I can find these outliers lol
