### ISSUE TITLE
Covariance propagation for safety filter

### ISSUE THREAD

**Issue by RudolfReiter** [shamilmamedov/flexible_arm#39]
I think it would be quite reasonable to propagate the model uncertainty at the last linearized solution of the safety filter trajectory w.r.t. the end-effector and elbow position, in order to define chance constraints.
Otherwise the safety bound would need to be quite conservative.
@shamilmamedov: What do you think?

**Comment by shamilmamedov** [comment]
Hi! 

Could you explain more about it? I haven't done it before. Is it similar to Kalman filter where we propagate uncertainty?

**Comment by RudolfReiter** [comment]
Hi! Yes, basically the same as EKF but with linearizing along the trajectory provided by the MPC. We can just reuse the EKF we have, but without measurements, just the prediction step. As an input it should get the whole trajectory. The output should be the covariances along the trajectory, most importantly on the p_ee and p_ellbow. Then, we can adapt parametric bound in the MPC and in the safety filter. We were also sloppy with this in our last paper, however, no one spotting the sloppynes ;)


That should be fairly straight forward I guess?

**Comment by shamilmamedov** [comment]
One more question, do we also linearize the map from the state to the output, i.e., to p_ee and p_elbow? And represent it as [p_ee, p_elbow] = C x ? Is there a chapter about it in Moritz notes on Numerical Optimal Control?

**Comment by shamilmamedov** [comment]
Hi Rudi! Do you want to do covariance propagation inside the OCP/MPC or outside? In the paper, I added 'Constraint tightening' to Appendix, can you math and confirm that it's what you had  in mind

**Comment by RudolfReiter** [comment]
I will reformulate it quite a bit but basically it is right!

**Comment by RudolfReiter** [comment]
Ok! Yes, works for both

**Comment by shamilmamedov** [comment]
I have implemented, it was straightforward. Nevertheless, can you give a look in the pending Pull-Request?

**Comment by RudolfReiter** [comment]
Not followed any more. Things we tried are the following:
1.) Using new acados formulation "zoro" -> Too many status 4s. Not really debugg-able. Quite immature acados feature
2.) Covariance propagation by hand. Takes too long to compute.

General problem: hard to tune COV matrices.
